__title__ = "Responder-Login"
__description__ = "User session management for Responder"
#__url__ = "Not yet :)"
__version_info__ = ("0", "0", "1")
__version__ = ".".join(__version_info__)
__author__ = "Yamato Nagata"
__author_email__ = "chickenwingswillfly@gmail.com"
__maintainer__ = "Yamato Nagata"
__license__ = "MIT"
__copyright__ = "(c) 2019 by Yamato Nagata"
